### ISSUE TITLE
Clock is not settable

### ISSUE THREAD

**Issue by juergen-schuch** [sker65/goDMD#23]
Not possible to set the time
after adjust time and date with remote control or the button
the displayed time starts always wit 17:30
Setting for i.e. time display hh:mm / hh:mm:ss works 
firmware is newest : goDMD-1.01.hex
date is 29.04.43 although in setting menue the year is correct: 2015

**Comment by sker65** [comment]
Possible hardware error. RTC adjusts are written to the rtc modul directly when menu is closed.
in this sense time / date adjusts are different from other options, which are written to file.
