### ISSUE TITLE
Pixel für FB Anzeige per Menü deaktiveren

### ISSUE THREAD

**Issue by master-of-chaos** [sker65/goDMD#24]
Anscheinend registriert der IR Empfänger auch Signale anderer Fernbedienungen .
Hier wäre es schön, wenn man die Signalisierung des Empfangs durch den linken obersten Pixel per Setting deaktivieren könnte,

**Comment by sker65** [comment]
Wird in einem der nächsten Releases supported werden.

**Comment by sker65** [comment]
fixed in 1.03
